config/routes.rb
Rails.application.routes.draw do
  resources :furkans
  root "furkans#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/furkan.rb
class Furkan < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/furkans_controller.rb
class FurkansController < ApplicationController
  before_action :set_furkan, only: [:show, :edit, :update, :destroy]

  # GET /furkans
  # GET /furkans.json
  def index
    @furkans = Furkan.all
  end

  # GET /furkans/1
  # GET /furkans/1.json
  def show
  end

  # GET /furkans/new
  def new
    @furkan = Furkan.new
  end

  # GET /furkans/1/edit
  def edit
  end

  # POST /furkans
  # POST /furkans.json
  def create
    @furkan = Furkan.new(furkan_params)

    respond_to do |format|
      if @furkan.save
        format.html { redirect_to @furkan, notice: 'Furkan was successfully created.' }
        format.json { render :show, status: :created, location: @furkan }
      else
        format.html { render :new }
        format.json { render json: @furkan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /furkans/1
  # PATCH/PUT /furkans/1.json
  def update
    respond_to do |format|
      if @furkan.update(furkan_params)
        format.html { redirect_to @furkan, notice: 'Furkan was successfully updated.' }
        format.json { render :show, status: :ok, location: @furkan }
      else
        format.html { render :edit }
        format.json { render json: @furkan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /furkans/1
  # DELETE /furkans/1.json
  def destroy
    @furkan.destroy
    respond_to do |format|
      format.html { redirect_to furkans_url, notice: 'Furkan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_furkan
      @furkan = Furkan.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def furkan_params
      params.fetch(:furkan, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/furkans_helper.rb
module FurkansHelper
end

app/views/furkans/_form.html.erb
<%= form_with(model: furkan, local: true) do |form| %>
  <% if furkan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(furkan.errors.count, "error") %> prohibited this furkan from being saved:</h2>

      <ul>
      <% furkan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/furkans/edit.html.erb
<h1>Editing Furkan</h1>

<%= render 'form', furkan: @furkan %>

<%= link_to 'Show', @furkan %> |
<%= link_to 'Back', furkans_path %>

app/views/furkans/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Furkans</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @furkans.each do |furkan| %>
      <tr>
        <td><%= link_to 'Show', furkan %></td>
        <td><%= link_to 'Edit', edit_furkan_path(furkan) %></td>
        <td><%= link_to 'Destroy', furkan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Furkan', new_furkan_path %>

app/views/furkans/new.html.erb
<h1>New Furkan</h1>

<%= render 'form', furkan: @furkan %>

<%= link_to 'Back', furkans_path %>

app/views/furkans/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_furkan_path(@furkan) %> |
<%= link_to 'Back', furkans_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Testo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>